const grabbedData = [ { name: 'Katie Lou Samuelson',
school: 'UConn',
POINTS_PER_GAME: '20.1',
FIELD_GOAL_PERCENTAGE: '47.3',
REBOUNDS_PER_GAME: '7.8',
THREES_MADE: '30',
THREE_PERCENTAGE: '40.5' },
{ name: 'Teaira McCowan',
school: 'Mississippi State',
POINTS_PER_GAME: '17.0',
FIELD_GOAL_PERCENTAGE: '69.4',
REBOUNDS_PER_GAME: '12.7' },
{ name: 'Megan Gustafson',
school: 'Iowa',
POINTS_PER_GAME: '26.5',
FIELD_GOAL_PERCENTAGE: '74.7',
REBOUNDS_PER_GAME: '12.5' },
{ name: 'Asia Durr',
school: 'Louisville',
POINTS_PER_GAME: '22.5',
FIELD_GOAL_PERCENTAGE: '47.0',
THREES_MADE: '34',
THREE_PERCENTAGE: '36.6' },
{ name: 'Arike Ogunbowale',
school: 'Notre Dame',
POINTS_PER_GAME: '23.1',
FIELD_GOAL_PERCENTAGE: '47.9' },
{ name: 'Napheesa Collier',
school: 'UConn',
POINTS_PER_GAME: '18.6',
FIELD_GOAL_PERCENTAGE: '59.3',
REBOUNDS_PER_GAME: '10.5' },
{ name: 'Kalani Brown',
school: 'Baylor',
POINTS_PER_GAME: '15.0',
FIELD_GOAL_PERCENTAGE: '61.5' },
{ name: 'Alanna Smith',
school: 'Stanford',
POINTS_PER_GAME: '19.4',
FIELD_GOAL_PERCENTAGE: '58.5',
THREES_MADE: '28',
THREE_PERCENTAGE: '50.9' },
{ name: 'Cierra Dillard',
school: 'Buffalo',
POINTS_PER_GAME: '25.4',
ASSISTS_PER_GAME: '4.9',
THREES_MADE: '33',
THREE_PERCENTAGE: '39.3' },
{ name: 'Kristine Anigwe',
school: 'California',
POINTS_PER_GAME: '22.2',
FIELD_GOAL_PERCENTAGE: '52.1',
REBOUNDS_PER_GAME: '13.7' },
{ name: 'Teniya Page',
school: 'Penn State',
POINTS_PER_GAME: '19.8' },
{ name: 'Bridget Carleton',
school: 'Iowa State',
POINTS_PER_GAME: '17.9',
ASSISTS_PER_GAME: '4.2',
REBOUNDS_PER_GAME: '8.7' },
{ name: 'Allazia Blockton',
school: 'Marquette',
POINTS_PER_GAME: '17.4',
FIELD_GOAL_PERCENTAGE: '48.3' },
{ name: 'Kenisha Bell',
school: 'Minnesota',
POINTS_PER_GAME: '19.5',
ASSISTS_PER_GAME: '4.5' },
{ name: 'Tynice Martin',
school: 'West Virginia',
POINTS_PER_GAME: '17.5',
THREE_PERCENTAGE: '44.4' },
{ name: 'Jessica Shepard',
school: 'Notre Dame',
POINTS_PER_GAME: '16.0',
FIELD_GOAL_PERCENTAGE: '62.1',
REBOUNDS_PER_GAME: '9.8' },
{ name: 'Maci Morris',
school: 'Kentucky',
POINTS_PER_GAME: '16.0',
THREES_MADE: '34',
THREE_PERCENTAGE: '44.2' },
{ name: 'Sophie Cunningham',
school: 'Missouri',
POINTS_PER_GAME: '15.5',
FIELD_GOAL_PERCENTAGE: '45.0' },
{ name: 'Kennedy Leonard',
school: 'Colorado',
ASSISTS_PER_GAME: '7.3' },
{ name: 'Naomi Davenport',
school: 'West Virginia',
FIELD_GOAL_PERCENTAGE: '46.2',
REBOUNDS_PER_GAME: '8.0' },
{ name: 'Chloe Jackson',
school: 'Baylor',
ASSISTS_PER_GAME: '5.9' },
{ name: 'Paris Kea', school: 'North Carolina' },
{ name: 'Marina Mabrey', school: 'Notre Dame' },
{ name: 'Lashann Higgs', school: 'Texas' },
{ name: 'Mariya Moore',
school: 'USC',
ASSISTS_PER_GAME: '3.7',
THREE_PERCENTAGE: '33.8' },
{ name: 'Brianna Turner',
school: 'Notre Dame',
FIELD_GOAL_PERCENTAGE: '59.1',
REBOUNDS_PER_GAME: '7.8' },
{ name: 'Anriel Howard',
school: 'Mississippi State',
POINTS_PER_GAME: '16.1',
FIELD_GOAL_PERCENTAGE: '54.4',
REBOUNDS_PER_GAME: '8.3' },
{ name: 'Caliya Robinson',
school: 'Georgia',
FIELD_GOAL_PERCENTAGE: '45.4',
REBOUNDS_PER_GAME: '9.0' },
{ name: 'Sam Fuehring', school: 'Louisville' },
{ name: 'Alexis Jennings', school: 'South Carolina' },
{ name: 'Hallie Thome', school: 'Michigan' },
{ name: 'Kitija Laksa', school: 'South Florida' } ]

exports.grabbedData = grabbedData;